version: "3"

services:
  app:
    container_name: virtualoffice_app
    build: ./app
    ports:
      - "3100:3100"
      - "9229:9229"
    volumes:
      - ./app:/opt/app/

  client:
    container_name: virtualoffice_client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/opt/app/virtualoffice-client/src
      - ./client/public:/opt/app/virtualoffice-client/public
    links:
      - app
    tty: true

  mongo:
    container_name: virtualoffice_mongo
    image: mongo
    ports:
      - "27017:27017"   