openapi: "3.0.0"
info:
  title: Virtual Office
  description: Organize your professional services on line.
  version: 1.0.0
  license:
    name: MIT
servers:
  - url: /api
    description: Local development server
paths:
  /users:
    $ref: '../modules/users/users.yaml#/users'
  # securitySchemes:
    # ApiKeyAuth:
    #   type: apiKey
    #   in: header
    #   name: X-API-Key