openapi: "3.0.0"
info:
  title: Virtual Office
  description: Organize your professional services on line.
  version: 1.0.0
  license:
    name: MIT
servers:
  - url: /api
    description: Local development server
paths:
  /auth/google:
    $ref: 'modules/auth/auth.yaml#/auth-google'  
  /auth/google/callback:
    $ref: 'modules/auth/auth.yaml#/auth-google-callback'
  /users:
    $ref: 'modules/users/users.yaml#/users'
  /users/credentials:
    $ref: 'modules/users/users.yaml#/users-credentials'
   
    # securitySchemes:
    # ApiKeyAuth:
    #   type: apiKey
    #   in: header
    #   name: X-API-Key